Arte\ObertestBundle\Entity\SystemUser:
  type: entity
  indexes: {  }
  id:
    SystemUserId:
      type: integer
      generator:
        strategy: AUTO
  fields:
    email:
      type: string
      length: 255
      nullable: true
  oneToMany:
    watertanks:
      targetEntity: Watertank
      mappedBy: systemuser
  manyToOne: {  }
  manyToMany: {  }
